apiVersion: v1
kind: Secret
metadata:
    name: opencode-credentials
    namespace: opencode
type: Opaque
stringData:
    GOOGLE_GENERATIVE_AI_API_KEY: ENC[AES256_GCM,data:wBqmml1VTKmnRMFYidm2BDU4fcR3c3xTXPMpeN1SAxWrf6szG0b1,iv:uhvpLyd5YgQJoQPVe6wud+vRwJqpEZfrx6eL0rwUaxs=,tag:ij66sEp4NzP6CuzpglyGcg==,type:str]
    HERMES_ADMIN_KEY: ENC[AES256_GCM,data:PWYkEfKuZIZpmUothMRiW/qDoi4Z6J5IjOT58yP6IbWSg3VhLkWMa85ITcXFOh77qJq9E/E/epezlZoBH9QhQQ==,iv:bcICAXgSqMwNNIOEYz76EPcBDlzSPKhva6W4/1HRp28=,tag:QWJmObjWpM9NRXiPlgLg7w==,type:str]
    HERMES_FAMILY_KEY: ENC[AES256_GCM,data:BLMbYiboQhTfJYpd9EOK/0EwQOzZXyfLqb0LB6/5qf5QE0RGZk0LkITC2Ipw8Z3JHAvhI56yOo2re0xmxC8OqA==,iv:1BWW3HQN+XM7suFqqoE4fwnXTbUnBIjcdEVwDOyalYs=,tag:ziFw+3yDeHyw/I0YgI/AzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPR3pnbW1pcWZYbUtSb2w2
            QTAyRzBCbml1Y29yUk8zRFVoeGt4Ym52OUdFCmtQeEtvd0RDL29YMEFtMFlNWWMv
            ZFRXYXhmZ3M0NE4zZzliVDNsbHFyVWcKLS0tIEc4VVhLbmQxNUZkYU9JT2JCVjZn
            TUJyV2xHcjZVbkNCeWpmRE0zOVJzN1UKweF4PaKdMhB5SxkRghNTb0359dnEFFKV
            RnAErxrWlwjPWnpAUcMNoODZCPxhGaCMG4oBywxkx75ugY4RUD7SFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-17T02:29:05Z"
    mac: ENC[AES256_GCM,data:X6az6K12me4TXW6rqb/Fiat/MCTg44s61PPcI+fKzQ4SEo6jbkuoix+iqeNsIt+zLBwbZ0/JJdk1UEnkg3YVB4DMuFJ2r9qIoUBkU3h8KEHn8ZdYfUDZzMqkQv0ogbkWGAE5qTg0GAcrMi5iPgkhNJCgv+P7p/Zmigmzt0KxYQo=,iv:dP/mSyMNb5yk4vUa4WFkjcQRY4LqRFWnQpXTm1NrXaU=,tag:iqIarP5KQ2e4MbQbplpXnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
