mqtt:
  enabled: true
  host: 192.168.4.13
  user: mqtt_user
  password: Radha@143_mqtt

ffmpeg:
  hwaccel_args: preset-vaapi
  retry_interval: 60
  input_args:
    - -timeout
    - '15000000'

detectors:
  ov:
    type: openvino
    device: CPU

model:
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  width: 300
  height: 300
  input_tensor: nhwc

detect:
  enabled: true
  fps: 3
  width: 640
  height: 360

objects:
  track:
    - person
    - car
    - dog
    - cat
  filters:
    person:
      min_score: 0.6
      threshold: 0.7
    car:
      min_score: 0.6
      threshold: 0.7

snapshots:
  enabled: true
  retain:
    default: 30

record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 15
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 180
      mode: active_objects
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 180
      mode: active_objects

go2rtc:
  streams:
    garagedoor:
      - 'echo:curl -fsSL http://192.168.4.13:8123/api/camera_stream_source/camera.aarlo_garage_door
        -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3ZTk2NjE5MTMwOTE0MTBiOWNiY2U2NWU3YTRkYThhOCIsImlhdCI6MTc2NDE0MDEyNiwiZXhwIjoyMDc5NTAwMTI2fQ.Zci2no2QvgSK26-Vp9oecNo02pwQen87jnUcrFo0OXE"'
    frontdoor:
      - 'echo:curl -fsSL http://192.168.4.13:8123/api/camera_stream_source/camera.aarlo_front_door
        -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3ZTk2NjE5MTMwOTE0MTBiOWNiY2U2NWU3YTRkYThhOCIsImlhdCI6MTc2NDE0MDEyNiwiZXhwIjoyMDc5NTAwMTI2fQ.Zci2no2QvgSK26-Vp9oecNo02pwQen87jnUcrFo0OXE"'
    frontside:
      - 'echo:curl -fsSL http://192.168.4.13:8123/api/camera_stream_source/camera.aarlo_front_side
        -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3ZTk2NjE5MTMwOTE0MTBiOWNiY2U2NWU3YTRkYThhOCIsImlhdCI6MTc2NDE0MDEyNiwiZXhwIjoyMDc5NTAwMTI2fQ.Zci2no2QvgSK26-Vp9oecNo02pwQen87jnUcrFo0OXE"'

cameras:
  garagedoor:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garagedoor?video
          input_args:
            - -rtsp_transport
            - tcp
            - -use_wallclock_as_timestamps
            - '1'
            - -fflags
            - +genpts+discardcorrupt+igndts
            - -avoid_negative_ts
            - make_zero
          roles:
            - detect
            - record
    detect:
      enabled: true
    zones:
      Walkway:
        coordinates: 0,1,0.034,0.49,0.209,0.276,0.563,0.244,0.976,0.444,0.986,1
        inertia: 3
        loitering_time: 0
      notification:
        coordinates:
          0,0.596,0.207,0.287,0.419,0.273,0.664,0.343,0.954,0.539,0.942,1,0,0.998
        loitering_time: 0
        inertia: 3
    motion:
      mask: 0.267,0,0.192,0.124,0.541,0.145,0.972,0.406,0.96,0.104
      threshold: 64
      contour_area: 10
      improve_contrast: true
    review:
      alerts:
        required_zones: notification
      detections: {}

  frontdoor:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontdoor?video
          input_args:
            - -rtsp_transport
            - tcp
            - -use_wallclock_as_timestamps
            - '1'
            - -fflags
            - +genpts+discardcorrupt+igndts
            - -avoid_negative_ts
            - make_zero
          roles:
            - detect
            - record
    detect:
      enabled: true
    zones:
      maked_frontdoorbell:
        coordinates: 0,0.624,0.149,0.599,0.152,0.467,0,0.28,0,0,1,0,1,1,0,1
        inertia: 3
        loitering_time: 0
      notification:
        coordinates:
          0.001,0.671,0.161,0.616,0.182,0,0.371,0,1,0,0.998,0.993,0.589,1,0.556,0.579,0.348,0.56,0.414,0.784,0.561,0.789,0.586,1,0.221,1,0,1
        loitering_time: 0
        inertia: 3
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: true
    review:
      alerts:
        required_zones: notification
      detections: {}

  frontside:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/frontside?video
          input_args:
            - -rtsp_transport
            - tcp
            - -use_wallclock_as_timestamps
            - '1'
            - -fflags
            - +genpts+discardcorrupt+igndts
            - -avoid_negative_ts
            - make_zero
          roles:
            - detect
            - record
    detect:
      enabled: true
    zones:
      maked_frontdoorbell:
        coordinates: 0,0,0.473,0,0.546,0.239,0.723,0.325,0.963,0.713,1,1,0,1
        inertia: 3
        loitering_time: 0
      notification:
        coordinates:
          0.005,0.995,0.005,0.003,0.384,0.005,0.5,0.258,0.793,0.389,0.906,0.554,0.953,0.725,1,1,0.61,1,0.551,0.493,0.388,0.525,0.372,1
        loitering_time: 0
        inertia: 3
    motion:
      threshold: 60
      contour_area: 10
      improve_contrast: true
    review:
      alerts:
        required_zones: notification
      detections: {}

version: 0.17-0
semantic_search:
  enabled: true
  model_size: small
face_recognition:
  enabled: true
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: false
