apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-role
rules:
  - apiGroups: ["", "networking.k8s.io", "apps"]
    resources: ["namespaces", "pods", "nodes", "services", "ingresses", "endpoints", "deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage-role
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
