apiVersion: v1
kind: ConfigMap
metadata:
  name: nut-config
  namespace: nut
data:
  nut.conf: |
    MODE=netserver

  ups.conf: |
    [apc]
      driver = usbhid-ups
      port = auto
      desc = "APC Back-UPS ES 750"
      vendorid = 051d
      productid = 0002
      user = root

  upsd.conf: |
    LISTEN 0.0.0.0 3493

  upsd.users: |
    [admin]
      password = __ADMIN_PASSWORD__
      actions = SET
      instcmds = ALL

    [monitor]
      password = __MONITOR_PASSWORD__
      upsmon master

  upsmon.conf: |
    MONITOR apc@localhost 1 monitor __MONITOR_PASSWORD__ master
    SHUTDOWNCMD "/sbin/shutdown -h +0"
    POLLFREQ 5
    POLLFREQALERT 5
    HOSTSYNC 15
    DEADTIME 15
    RBWARNTIME 43200
    NOCOMMWARNTIME 300
    FINALDELAY 5
