apiVersion: v1
kind: Secret
metadata:
    name: nut-secrets
    namespace: nut
type: Opaque
stringData:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:vtgcRNzBKSSWPWOaoLJbAiMyYUqysCjT,iv:lNanqbD3QEFsJHf2xCPl0Wv9L5ccVR4m8mc++I557LA=,tag:01yTFhuxp6jVoz7q19g3Iw==,type:str]
    MONITOR_PASSWORD: ENC[AES256_GCM,data:Owe95aoND5FCN7eFwOoWoIwE1oQcbRUOj4Y=,iv:NNkM7axUBzoUOdthY1LFU1/1HbJvre/gSSmraPcn7Kc=,tag:0+8ZD7/qDV8Rvbp3YBRTrg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL0VxVGFHYXNLeWtoVERu
            cHhVb2V4aHdyQTdhZHhHS2NlU0QreHJOVFE4Cnd2Y2tZMGM5dEo0RHNsdTY4ZGll
            L2oxS3pvNVJvTHNIZDY1ZmRXSE5WbXcKLS0tIFA4WVRUNlZVK2ZIUnk4cE9oL3dI
            YVdZZmlGMnhiTlUwaWtrS2ZxU0NQZUUKRO9+DERidkEbMwcyLhlIWgKNF/RuAxX8
            ZEOuB/2Dqmvqp611u5M8GyG7KU9QBj9tt37vgcPkkmShQdJBSAh72A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T05:48:42Z"
    mac: ENC[AES256_GCM,data:LJI7h27/EqZ5EfsJFxmFbW+yMwb2IaUZ/18TaxT2y3Bd1pUW17n0wE5C6V2+HlBtjjfIc+9Lb4jJ7AtAEC8zZfsfY0E5MWZdsRf8Pk+lMzj0SCVbdOXjbcMzsJegL9+/PKijiDSfh0pl13+ZPqgpOKLtF9cJApZPRe6yRKFCWzg=,iv:PMY0IqvkjO//B9XV/vit4Mwb/YCfUSRnSH0t44hvztI=,tag:2Yfw4SQ5zrjVImDlNqIi+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
