apiVersion: v1
kind: Service
metadata:
  name: nut-server
  namespace: nut
spec:
  type: ClusterIP
  selector:
    app: nut-server
  ports:
    - port: 3493
      targetPort: 3493
      protocol: TCP
