apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:ZvO1/n9f3xMyZupyGKimItyoJZB7JofkqaZr4mGBnocaJAgBDsx+QgQVWpnElzBIcUX89b505SXK2rzLl0tNKg==,iv:gAATmsiqLmATlDvLEhX1gSGIXUWAhLaJMckmKI27k1E=,tag:7NB/7yHDS2K78UxsHgRoVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOFlFeUhiOEdCVFlsNkFy
            OWlLdzV5WnFZRDBuVUF2Z2JXOE1VdU10TkJvCjJudDBja1d3ODhlV0R4eUNmRXNM
            ZmhwaUdjaHNpTXlPSWozMFZDVGxyT00KLS0tIHpKN3N3Y3dFbUhGSE5oSHRyVmFY
            NTkzNXZpeE9pTDMyQ1lmeFNJUlJvUW8K+VVfNzmLVFqgijs1FPNmta5S/MSq4G3v
            oK74RVGlVkKBOzxNJ4IYhgtdLDe6vhg4O4wI7YStPfqix8ECZUnnnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T03:26:54Z"
    mac: ENC[AES256_GCM,data:bGtyL8ej1URQLKW6xUngXTow9x/Qi+XJ04XTkS2RV5qW4RH5MJ0aOlJpfpXkL4XYVJoYVQwyx1zoPo9P/l9P7GIIYafxLmdQBCRa8MlEMECp9er9W3r8uP2Z/tSDqynRtTsbWh1hcGuXQmF2T74afhO+JR+W8mI4uKWjKlFqwec=,iv:oFsWM5rgIgEunYrN3JWysSz0zOzBfljt/8+6GLcAGJU=,tag:ggEoqluZY4afFEAWY1XpgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
