apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vmagent/rbac.yaml
  - vmagent/configmap.yaml
  - vmagent/deployment.yaml
  - alloy-logs/rbac.yaml
  - alloy-logs/configmap.yaml
  - alloy-logs/deployment.yaml
