apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: miniflux
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:7+gJDDcYl5w57s/gLXls9/Du,iv:1KdTYqJCRSdmaPghnlSkvRcCGy5FqF0m6v9na7uclVw=,tag:C7GI3phUglfLXIo/0gVQqg==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:0vGNlf4=,iv:21In7X6FrO6+1Ue3YoAuP/ya571FNURE6E8JRIZXjlo=,tag:s6vvHOtr7W3GaCyJlYjGBQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:gII3bQHD5g1omlwhgPBqmI9r,iv:nWWOScHWGXNX2O74RR6x7/1LYykbggJOkr4sehc7P6Y=,tag:1QiX0MrmRK7+HdtNEUiFhQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:8khfqyTHphcE6GuPD+kieHcgPMKq95nc+XMPaCXZpdVY2atw1la+ud1lsIxwDC/AUXjkm+EtT1m9jEygAmLdJ+XZjeTUNHoRQi4zlqon7ck=,iv:QxmO4LISV6BcobxohW1zQIy+7s3GX2HtBTdogDFxcJs=,tag:Nuq+zSvAA6hc9F8Duw05/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTmFyQWdHVVlaU3VHckxj
            dnBxWS9Xck9ST01ZSStOUVA2cm9ZUVNwOGgwCjEvSUlKeXpaWGVZbWFoK2wvZlI5
            SjZuQVBkTC9oVTVJekRyS1ZZMG04dFEKLS0tIFFmRWlBTzY1WHM0SDZRNkdOQ3hU
            QnFjRlpXaG1jM2ZoK1UvVjAzWEhobDAKsElRPloCZ357jSusik2Z+riY8Fq8ei1Z
            Vl4Mw9oeCDjRqRb+S61IsEqxVGzu3TegkgkGSzxDwQFLFrNceU4E0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T05:48:42Z"
    mac: ENC[AES256_GCM,data:LW9pZgcjbRH4BwwumNnKlPUb9RvutgP5aetQEb3fkDEsBVoh0hFO0ORZdGPlq+eLNuaGVYpiegfrKncQxJo0HM8IcRmUUrTfLP/I5bqjOr+SIvcFxkz0KBXTTsMr0OZweQzAsKsnuOr7/wRySg2I/3LwvNacDIIhPGnzI0Hg21A=,iv:S5KD03sGNMxa7eV7iQAeMpZkE8zvyMotQHRYF5X7yM0=,tag:QQ20yclNoeTfruTrR6G4cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
