apiVersion: v1
kind: Secret
metadata:
    name: hindsight-mcp-auth
    namespace: hermes-family
type: Opaque
stringData:
    #ENC[AES256_GCM,data:avyVWwBj4N/DuZNq5gOMsrL7jvXlLQWCxQbAyeWkSDRS21BDyf13JFpvxX5yvKTvUuPn+HHtYb7rnA7UU1RJpSiiqQ==,iv:yk4pHThRdWFA+Qez8WtzvBHwwFve0kIVY0iPsAnBoZo=,tag:jjlw+jqDcMlxA/j04iZNeQ==,type:comment]
    #ENC[AES256_GCM,data:l8UI05H7Vv137aXiDxbHrSsAjNeki8/P8kEWKyWqeYqeskunsHpxqrBJ5gZQmo6S8vHyi8yDEtRJTmlG1Vtx2WSxwuuXPEuH2cgfuGI=,iv:sh7ck71s8CO4DnrsaHIJZ4Lvj78UCSzXqwfeeSCG/o4=,tag:h+yeCb+cXgwPpPXrRf8vpA==,type:comment]
    HINDSIGHT_API_KEY: ENC[AES256_GCM,data:HG5Njy1Zpq9O9Duu2MmzvM2n1vvb27MDdV5/9v9ecsvdn6nPR9jA9rNUQhV0aGPbdQlp,iv:eFHsRqBPuOwP1jovGR9zkWZaACUXcuH4RSgpWceRAEs=,tag:DDwsqr0EiE6gmjodAMbiPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTFJBUTZaMmlXT0h1WUdT
            WGRrVmMvWG0rRWU0MEJSdHh0aGM5OTVHSmxZCjlLa1RjWS9qNng1aXV6RUtZb1hP
            YWpzajlBTnpZTVJXWWN4ZUhjTXJnU1UKLS0tIDhxYzM2ZHFaZk5qWldOd0RNZml2
            SWk1Q2R5ZFRVZmRqWHl2V3ZrTDV6QzAKV2/26nAQhEb+SmJLeXoeFkxV8V91Ck1l
            L4yfbk1VfwVfG9YF2MXjrZmxkDczwmNmyx8G/x1jCDLcBvlsP0Jn7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T06:25:55Z"
    mac: ENC[AES256_GCM,data:ReVEYRerRXY969UCrOPn8/7u1s3GfRtmE9yLEe9tI9vQFbYKxpy7nCST3QEdmtH5Ly1XfA/SafOecVhHjBnF7Y4Qh0zzwO6d1qMHEbMhe3upVjIGy3c4f7pR2nMWrePdxpS+kL82QnxUs+OWlBw1WCJ3usELfhJXqSF2U76CYwc=,iv:gsziXbIfN5dTvTY3OJBsdEH1w8RVE+jjzYP61vKg8s0=,tag:XpJibGHRZd2cREvOF5ftzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
