apiVersion: v1
kind: Secret
metadata:
    name: hermes-family-credentials
    namespace: hermes-family
type: Opaque
stringData:
    API_SERVER_KEY: ENC[AES256_GCM,data:JEtDEvgaPzXMdu5g3dbyE1I7ZZ3WSh8wwMmN4nvrWcrp2xeEIAc1V3zHcu1rZXVwwxKL/HU5NknTL3Sxpw+ezw==,iv:Wn994ALnjFMeu2tzYLvvMKGepKQ9oRSrPPgWMm2G/NQ=,tag:g8SvFVf881nODcQ+8eF1Ww==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:opEBGQ7SiFqtQH4orMrCugGskBEG4sWuWxf/89esUcVfWDulFbY0l0dKLvDtZLlPm/bXFDs=,iv:IVd7QTZoIt75SeugP7rN7QCtzAtFh/Ct62GHobj8MZM=,tag:kJigAJCC5sJvfg7YMF3zVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMFhnNWo1aWZoRStlYmRR
            MXR2cmd0T1N1UVIxbjI3SmNnVnFVWEVlRFVnCkJDc3pqS0tQUFRNa2lNMVh5M3Zj
            UWc5QUxZK2hNTnlUWDY1SFdUQS9PbU0KLS0tIFNCbDN2ZFhnRTdzZ3BTNWJZdWtJ
            RGZHSlFLbFBsQ0NnQWxNKytybTZNek0K2sUepwgE10hRfUjLJoYeN7KbmY5oeuSA
            BATe0DLVgtr/bS8DRPg+IVh78vPHWiyT3QUMBXDRJpzxspTGGwVOMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-16T02:21:15Z"
    mac: ENC[AES256_GCM,data:jn92k6yMNZCAg1IHmN+3kctSxHbPpju1Iul7zQFysFF1OMaTUpg45m/J9W/edmzJxZbMz2kDXIp3wPgqcqAJqIphMcdZHPlcIX5pec/XQysWQch/qdXu2cY7L068HRhcqVtqjHI7cSXIK+kb3BEatist1EWIVzw5xvoOu2Ei638=,iv:KbAvAqq1TTk7+Oy6vvs6C2o5p0pTo0ff4DayWXfHwok=,tag:6H1m7gIGEKgatf5/vADWmQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
