apiVersion: v1
kind: Secret
metadata:
    name: postgres-creds
    namespace: mem0
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:8tJBmQ==,iv:wMeZffqBB7NTOWmu04tKkdngpP/BmzqDb5OeVjnCGvA=,tag:d/LJgMs54bt81XT2Y6nKpg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:6YJNXw==,iv:jUVTcr3G8C/taOESSSBMujAsVKCRvPPpEKjEQydjvyA=,tag:6b0LBmOglggEAyeXWPoWZQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:zf4Z2hQoR7xB7kmDTsk=,iv:6aVw9uji9DlhLKQhoVd+a/TfUgF5UyIaVKgMaJj095A=,tag:ncz8mnqgAY/rJlYAvyrgDA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:2GQjfZL7iD9ob4vrX2fAh+eCCn40YAm+G92vhs4DwETBTYy28el4GukZV/GBcCIwaa5gZRTfKikfvFNc7eo9LEZdmx/b6ifkCx3kzg==,iv:gu4lLtO7lC4y3wuLpkWHZIW9+mYlbJZSGp2/G0HQT20=,tag:/br6YHv5A80DQ9f2DxayPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMU9HdG5XbFBRL0ZzeXFQ
            S1k4cDQwcTh2VlY4Z28yWUFVN1RvV2d2NVhvCi9Hd0lSRTNMVldFUkJrVVhyS1pu
            Rnc5YVJTVjUwVll5WnRvbVVBbkE0NDgKLS0tIGpCZ1B2ZnpaY3ZuVHBLTGkwa20z
            K2lLNHpUQTJNL2dwKzcwR3RxS1lUbUUK92tDqlzDYrHKItMGnpQ/P34Cn4KNdWbj
            IzD/XGrymGQ6zzcQodrZxaBz9CmbVrnFdz29h692NKGE5cUtUEfbWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T06:41:06Z"
    mac: ENC[AES256_GCM,data:HSfsyYK+SD6bljvIMjvNcxHaJvsJT1UuhBOH2YK9gPQ1aDp3Hy4DibSsDB/dUlAo3+eGACnhX+WJcvmx+6DVBRBDFqR4AlbXtkj3dg0NOiV4vV8C5nw6Kj+3ZnqmlumLeoFmgkTDUEutS5UBQ/fFXnLmbL7Kv5qHi5rLOcV8Jr0=,iv:M2gqH2FSDpkZv0xlURz23l6wYvKjZGyuoFXHJKgK/kU=,tag:qYyiP+K7uDTjenc2sIzeTw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
