apiVersion: v1
kind: Secret
metadata:
    name: postgres-creds
    namespace: mem0
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:cisEAw==,iv:wlBfM12Tu2cqI8p9V1EV4ihLsUUrVrLFeExfkNGEXv4=,tag:Dy+/vu3ie5a/V20P65G1kw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:9ihDoQ==,iv:U+VJO/i1x3q0JDcjN12k0rsgYUEkAYhVIaJs+dY+HAo=,tag:xRNtBlBZv9Bzr7jCl+Wd+Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wiyVyHlNxJMkMAXtuko=,iv:wIJUJGEmIlaPjMXenUVp79gKvfvlURaKyXCxuBUKJxo=,tag:NETEqvyucDxC92/RBF95wA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcUM1TGhWZ1p1bXBnczd5
            MGxxaURBdU1yWHpPeU02cFM5cUVETXp6d0hrCkpEWVBVNy9wS0g3NEdIZEZUamwv
            em4xcTByU3ZvbTR6RkFvZ0RPanNhNjgKLS0tIEpzUmZwSGsxNDN4VTBvdFFISURX
            ZGZrUXVhQmQ5RHlIYjNBY2M3Rys1N1EKrFrnEVdqZL7rAj/PpKrlyFGlXoyIkn3c
            nHg6cjv0633NQh1nYuofUfrhRWD9E3973V/6Lt3YuKkBTFIgUG99QA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T05:48:42Z"
    mac: ENC[AES256_GCM,data:vHnXPvwZ1dCJqN0fuxTfBj5bx7aVqyWBdMpehfnKW37hTb4VB5+frNaGNAX6tkOnstgcsdzdxpGfDUNMD3mBwag6TbRhihQ9VDVzCmLzoH7KZ1DLhiI6vK3G/4UPlSL8MyEQOfv2y5oBR8RPCv+1iXJ+bxlmqfGeuTvxkXFB4wg=,iv:ynrN/OHhrCXti1b13w61RQozAyAMYZVHl+6mq7s+iAE=,tag:0fiQMQ7r8dGZnXPLmRwNtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
