apiVersion: v1
kind: Secret
metadata:
    name: postgres-creds
    namespace: mem0
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:OVtD0A==,iv:s3OPlGDdZA9PMAwk4oSeWUGC8hU9J0Uy+ZI9uAzf+Ss=,tag:wMT9ZMk+YGkuKCs9jS+ssg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:cOudAw==,iv:UhXbUhzlkyQv3Yqpsjj0UkvYT9rDkh+pmTXHyllEg7U=,tag:1hN3sUOJXbmgl2JkTRtZRQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:mcbLiE4NQN32W+VaI+l2C/5NHPYKtP+NM4eWpV9NRFI=,iv:j+9Wf/SjkIcvBav8dzfGb0FXdozVwpA7fVv6ZlHIeWs=,tag:ePHT/tq1lsNSA9x1akkoDg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:DGV9YZU3ut6R+rWAsZTL6ZjEtwfZSvIMe29IY6lc+nJ+76/ae6wo0QozkuyBz0F/1PEQoZYXjdpcvFS/GFAu9WH+EdFmVTHmSVODQRraZAv+lB5LFvaUoLdmOZw=,iv:WRo/GrfgCmCBCxVKt1EhF1kzJZsVPnPuj7hk5P7bCGY=,tag:w8ByfRnOy6miIzg10hHGnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNFZscWlwM2RmSEJ5bm5p
            elFIQ2p4OWE1ckJOdEt2TFA4emt2dTVYL1M0CjhRZklLN2FKSjNJMUR0OExOeW9N
            RjFaVGZJQU9jQk1BeVY4dlRmeDZuWjgKLS0tIFBWWjV5a3V5Zm0xdmtxdmtCK3Z2
            R21PRmlqci91SVZLbFpBQjBsaUNGUXcKAO2TrDXP3PciRYH9LLeD6cbbHSGr62+6
            /XOlL5eJuZasvmwvsdJAZm3ncbHzKcbvmizG7oPwdaUYdNzKhQG6LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T06:59:30Z"
    mac: ENC[AES256_GCM,data:B5atqkbbrTTAdOKCtdrc6yoYRQGwgpWGCrcj+ljgUc3nYwI7240VBWGN/I74Fe+CX/G06e9LVXHSU0bDH67r+aM22unQ5loPvBueQzmlNFmXl9J/KwKp89akMHG75eJXH+WPAv33wcj0tvnX2O2+6Cw0GPp83kdt45QmH1GuVH8=,iv:hIdYBt7TUDWEQMZL8oLfohJOpp99as8OcMU32wP9cEE=,tag:tvs0iFZB/dfRYArYNeyAEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
