apiVersion: v1
kind: Service
metadata:
  name: karakeep
  namespace: karakeep
spec:
  type: NodePort
  selector:
    app: karakeep
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30801
      name: http
