apiVersion: v1
kind: Secret
metadata:
    name: karakeep-app-creds
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:aRFmM9CVqgxyfp38a7embBYDLx8aziPaYn7XijcvE1nh61uYwL8Otz2TD8QcbgeJvgEk6znQbzso3VdXYZg9lQ==,iv:LMf1zFty+vbJ1Gkc2hswmeGh9BnXgu03GBRWRMKgPgY=,tag:W+IFTcFuj+jyrUlipNfvlQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:URKqqguaRGIdV9kUnzaVdAi2Subqj5hsFH256shkBdI/2aNIkcp+rXmkgyYetKTwgU4zmicPC4QnsqZ2ntuFXzic7MvvLQrgDQO14yJS1b6AlLXTqPskScaU+kpHsKBBLhg97w==,iv:6X+WZFKgO36IeWp9Fa8S40AQarb0WaIWF9hVogSVdX0=,tag:l2qP6FQ5i3BotziiPMKuaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTG9qWnZtcFBvWllNUExS
            b1Uwbmw5dHR6R0dGcHFYS1BoMDNBV2FuMmhBCkc4aHU4N0tjSFkwQ3k1Ky92ZTVp
            NEdxazJTL3hpU0dEZzR2eG0zOGlteUUKLS0tIHNlMjdocndJT3dZMkVIU1d3VFMr
            NkU2cGJaUlIrei9EaFVqejZGOHJ3WkEK+haAZI7HEo2WuoTSgvq+83Qj3mTadThU
            ufMpXLceWrfx9mSwHZMBciFBeo46w1CXNTcr0ZJt49qGeFmDDpiIxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T05:03:41Z"
    mac: ENC[AES256_GCM,data:QyWugUhOPbB58nef1xz41UkAE+vczhPW4f3WdBJmpqUuIUjtyzErHw45Mr+40ljsRKquPdg5qanI2/Nt6mKf6DD28+yZmBhBNFQqla7+njpb1YUvAE9gZLZeIw/J7FlovO2cw/6h0IrVXrKmtS+m5NssO+uYIV7d25Vkxg626ho=,iv:52m03Fj7BRbHuWaUk/hpbZOa8iJ9s/kvzXOeE/KnUqQ=,tag:F9OFcZcRephWUsq2x7MUGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: karakeep-postgres-creds
    namespace: karakeep
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:zB804t/y3wg=,iv:KcQcXNfaGLQbs9oHRZMaqKGZa+ypWFGNAq6mtmHMF7w=,tag:1dN7326JrtuK26r5IgYbvw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:33pmwdbAQLg6Y5/xGcMC16ydCTo/qg+ls67NzpB/ZAg=,iv:GYF7+nSVZe96RrDHuPOoXiBW2sep3YLJQw6O061pjmg=,tag:c1kZUi4nihaPN+elRvPpOQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:zJjJDtbmXBY=,iv:nYmLpeArX7wEs/MucWfIgKHc5hUzt6lX0bF5JJttqbo=,tag:BDb3YSvDBvLt3rcCfRe3nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTG9qWnZtcFBvWllNUExS
            b1Uwbmw5dHR6R0dGcHFYS1BoMDNBV2FuMmhBCkc4aHU4N0tjSFkwQ3k1Ky92ZTVp
            NEdxazJTL3hpU0dEZzR2eG0zOGlteUUKLS0tIHNlMjdocndJT3dZMkVIU1d3VFMr
            NkU2cGJaUlIrei9EaFVqejZGOHJ3WkEK+haAZI7HEo2WuoTSgvq+83Qj3mTadThU
            ufMpXLceWrfx9mSwHZMBciFBeo46w1CXNTcr0ZJt49qGeFmDDpiIxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T05:03:41Z"
    mac: ENC[AES256_GCM,data:QyWugUhOPbB58nef1xz41UkAE+vczhPW4f3WdBJmpqUuIUjtyzErHw45Mr+40ljsRKquPdg5qanI2/Nt6mKf6DD28+yZmBhBNFQqla7+njpb1YUvAE9gZLZeIw/J7FlovO2cw/6h0IrVXrKmtS+m5NssO+uYIV7d25Vkxg626ho=,iv:52m03Fj7BRbHuWaUk/hpbZOa8iJ9s/kvzXOeE/KnUqQ=,tag:F9OFcZcRephWUsq2x7MUGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: karakeep-meili-creds
    namespace: karakeep
type: Opaque
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:QNIYOG41uYiXgcBSrXU4fiLmHK4pHBAJmWLf37F8fDKkNrhEh9gwZHiQkvwjAbYiaEbx25Qm+MRSPR+zk9MKVg==,iv:OrNXYMbCnZFncKGJ38JXZSs3j6T5FZMnwR7QOic63r8=,tag:t2gqKad3FVGEAXzDgHQZLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTG9qWnZtcFBvWllNUExS
            b1Uwbmw5dHR6R0dGcHFYS1BoMDNBV2FuMmhBCkc4aHU4N0tjSFkwQ3k1Ky92ZTVp
            NEdxazJTL3hpU0dEZzR2eG0zOGlteUUKLS0tIHNlMjdocndJT3dZMkVIU1d3VFMr
            NkU2cGJaUlIrei9EaFVqejZGOHJ3WkEK+haAZI7HEo2WuoTSgvq+83Qj3mTadThU
            ufMpXLceWrfx9mSwHZMBciFBeo46w1CXNTcr0ZJt49qGeFmDDpiIxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T05:03:41Z"
    mac: ENC[AES256_GCM,data:QyWugUhOPbB58nef1xz41UkAE+vczhPW4f3WdBJmpqUuIUjtyzErHw45Mr+40ljsRKquPdg5qanI2/Nt6mKf6DD28+yZmBhBNFQqla7+njpb1YUvAE9gZLZeIw/J7FlovO2cw/6h0IrVXrKmtS+m5NssO+uYIV7d25Vkxg626ho=,iv:52m03Fj7BRbHuWaUk/hpbZOa8iJ9s/kvzXOeE/KnUqQ=,tag:F9OFcZcRephWUsq2x7MUGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
