apiVersion: v1
kind: Secret
metadata:
    name: karakeep-app-creds
    namespace: karakeep
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:Rni3dhxjJtqvV1jfVAfbj66qfucSd1Cr74Pl/3OVSnmVkRiV9LTvZKhv5Okq3LN0d7Hxk8UTs1+jDyOv/LlxPg==,iv:Gmau2dJiGoc0dxEP+APOcdgTqtTpCHoC/rdPkbKAHnk=,tag:+iVilK4DjSil5CLQbHfMqg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:CWMMJKXNvLBfnVZDf2BrpVf2ev0kpvqaFOTaTRvA1Uo3FgM5Xf/BUQzGdegWw+JEW2g1AGZlx4YTyAIs669pAtm90ClLSdq1HctsorTcc1NXjYZ2ja11btVOsN/GzsZD7+i54Q==,iv:7CPoJGo1610wnL/diElnI25GLXmJfsP2CKJXmN1AMTg=,tag:VF/rIuahiFkYqhpIb9h6Hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRE9KNVhhNDR0TGRNY3Zq
            b0hyUE43dXVHNis1ZEdESzE2Ni9OUlFESVVnCkQzK2pEWWNmZzJmM0dlYTN0K2ph
            SzUzeGJKcVNDYnQ1SURnVFlCQ0dBOW8KLS0tIHVrNlA4aHltTnpSL2liYWlZN1RV
            SFRZREJvVTBabVBmSzIxQ0hCSFpJcGcKFqxt/J/VI7wUYNjdA+fhvNCZ3dyQeUy1
            2ZvxaR9tJhBbftw0S4KtaiQ1/3SIKjYNik/gP1YTebnmHO1xz+1rRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T05:32:30Z"
    mac: ENC[AES256_GCM,data:2iVvrEHdZCz2S0F/472tNBJ5BCLaaPmiGhPRX03ZlfIMeM0PgMZEuyogecUKhg/NtMGUjTK2f2kdPNMPLyKU8xL+F0Rj70nNwAc/xgdDjz7jtJZzPbKmU5hXNE0utLgQbAfP6Hnl6/q//xSeIHQz4YDAFBDLkPelqgEq2FvMAFI=,iv:PGuIOeb2r2z+RODirZz4iDmEq53CF0edT7I1qv8os1s=,tag:dISWvEgfqJK+sIbE4kHMXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: karakeep-postgres-creds
    namespace: karakeep
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:JpEQN+gtxVs=,iv:fyOOLjn4AzjqErzNqhMzyJEe6uVPZ2/sDJNLlgt41JM=,tag:zzWcpYk0IYFys7/4NHzLjA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:L2dn5syPsPubhPgbJNVPiFZQ+dRy5NYjHZW+IzirjGE=,iv:El+wBZOQrUYetuwozpsbhhncb6e+zlUqBrnGgNTeUEk=,tag:xcSssxInc8+omYxNVDcUaA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:sF1FJD8GD5Y=,iv:0Do80Fn8teV34STHVCljFz1mCdR2nVkORgbudqqpmuo=,tag:rszS1gXwPD7qhzAyKKIrMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRE9KNVhhNDR0TGRNY3Zq
            b0hyUE43dXVHNis1ZEdESzE2Ni9OUlFESVVnCkQzK2pEWWNmZzJmM0dlYTN0K2ph
            SzUzeGJKcVNDYnQ1SURnVFlCQ0dBOW8KLS0tIHVrNlA4aHltTnpSL2liYWlZN1RV
            SFRZREJvVTBabVBmSzIxQ0hCSFpJcGcKFqxt/J/VI7wUYNjdA+fhvNCZ3dyQeUy1
            2ZvxaR9tJhBbftw0S4KtaiQ1/3SIKjYNik/gP1YTebnmHO1xz+1rRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T05:32:30Z"
    mac: ENC[AES256_GCM,data:2iVvrEHdZCz2S0F/472tNBJ5BCLaaPmiGhPRX03ZlfIMeM0PgMZEuyogecUKhg/NtMGUjTK2f2kdPNMPLyKU8xL+F0Rj70nNwAc/xgdDjz7jtJZzPbKmU5hXNE0utLgQbAfP6Hnl6/q//xSeIHQz4YDAFBDLkPelqgEq2FvMAFI=,iv:PGuIOeb2r2z+RODirZz4iDmEq53CF0edT7I1qv8os1s=,tag:dISWvEgfqJK+sIbE4kHMXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: karakeep-meili-creds
    namespace: karakeep
type: Opaque
stringData:
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:OW5KJyCB/Ud/9SM3yiefB8D0jhd4zoz/zgFuKA9uSYRbX7iuxDPDgD4wIfnGey8I4+rO2K+gvxBF2NiFdt1EDw==,iv:J7bdIunbWoR3YE+A+PV9nHKktDKJNhdiCnQ41kV5PfU=,tag:Gl8znlk9UUHM1VU/3do9Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRE9KNVhhNDR0TGRNY3Zq
            b0hyUE43dXVHNis1ZEdESzE2Ni9OUlFESVVnCkQzK2pEWWNmZzJmM0dlYTN0K2ph
            SzUzeGJKcVNDYnQ1SURnVFlCQ0dBOW8KLS0tIHVrNlA4aHltTnpSL2liYWlZN1RV
            SFRZREJvVTBabVBmSzIxQ0hCSFpJcGcKFqxt/J/VI7wUYNjdA+fhvNCZ3dyQeUy1
            2ZvxaR9tJhBbftw0S4KtaiQ1/3SIKjYNik/gP1YTebnmHO1xz+1rRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T05:32:30Z"
    mac: ENC[AES256_GCM,data:2iVvrEHdZCz2S0F/472tNBJ5BCLaaPmiGhPRX03ZlfIMeM0PgMZEuyogecUKhg/NtMGUjTK2f2kdPNMPLyKU8xL+F0Rj70nNwAc/xgdDjz7jtJZzPbKmU5hXNE0utLgQbAfP6Hnl6/q//xSeIHQz4YDAFBDLkPelqgEq2FvMAFI=,iv:PGuIOeb2r2z+RODirZz4iDmEq53CF0edT7I1qv8os1s=,tag:dISWvEgfqJK+sIbE4kHMXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: karakeep-sync-creds
    namespace: karakeep
type: Opaque
stringData:
    MINIFLUX_TOKEN: ENC[AES256_GCM,data:XQe5geRVkvVaFNO2eT3MNMBYOsEhClwyMq3jwlmgRx+MrizV2RBjGw7agaN/JQPCqy2Xhg6TrSBvRPKcaCLYxQ==,iv:Slu6npYx8ytl4tXy1G3SwGTh6gH4FXKG9DlsB4mt88Q=,tag:/YGcuzPY151VYw7tmSNfCw==,type:str]
    KARAKEEP_TOKEN: ENC[AES256_GCM,data:mvHDYohfuBQbDP64nA7fP1t+foP/GRrr30l93yhO7gbu5C07X+8/E7m0bXif/40hc6bv86QTMkgc,iv:SqdBZcB+I6u18kXAiQNl2eUNNwO8Qk+44CTZTIGue7w=,tag:d9wblnWp8vKyatXO+R3RMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRE9KNVhhNDR0TGRNY3Zq
            b0hyUE43dXVHNis1ZEdESzE2Ni9OUlFESVVnCkQzK2pEWWNmZzJmM0dlYTN0K2ph
            SzUzeGJKcVNDYnQ1SURnVFlCQ0dBOW8KLS0tIHVrNlA4aHltTnpSL2liYWlZN1RV
            SFRZREJvVTBabVBmSzIxQ0hCSFpJcGcKFqxt/J/VI7wUYNjdA+fhvNCZ3dyQeUy1
            2ZvxaR9tJhBbftw0S4KtaiQ1/3SIKjYNik/gP1YTebnmHO1xz+1rRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T05:32:30Z"
    mac: ENC[AES256_GCM,data:2iVvrEHdZCz2S0F/472tNBJ5BCLaaPmiGhPRX03ZlfIMeM0PgMZEuyogecUKhg/NtMGUjTK2f2kdPNMPLyKU8xL+F0Rj70nNwAc/xgdDjz7jtJZzPbKmU5hXNE0utLgQbAfP6Hnl6/q//xSeIHQz4YDAFBDLkPelqgEq2FvMAFI=,iv:PGuIOeb2r2z+RODirZz4iDmEq53CF0edT7I1qv8os1s=,tag:dISWvEgfqJK+sIbE4kHMXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
