apiVersion: v1
kind: Secret
metadata:
    name: hindsight-mcp-auth
    namespace: hermes-agent
type: Opaque
stringData:
    #ENC[AES256_GCM,data:4B0mb6ZPeHpM+5AfnTpOMgyvfU4YmVDQYvjl03gs++YathTXbB4u1gZlT3BZVVP92wzeRhCgHc3cpyPFz+yXBhTN2Q==,iv:pNv+SgJxxEvw1mlnu0N8n/0MOVPgfrpQgkqBdWqLPjg=,tag:9x2dZAsBZlxeovhna5g3DA==,type:comment]
    #ENC[AES256_GCM,data:x4SsGe0pS0GCn2lIR5EoZ0mEeH0pDgZ7EQib/pR4SLIQ1UfXUDdgS5M80s46ELyXLPGtBSc0LAPcpeHjADHXt2T5OEQoGs1siQponJU=,iv:BtCTK4RRS7kMjqS/6EZ26vhlbSWGFEM62mW4PNRnktA=,tag:5pnXdvY3LstIuJYb6VV8Zw==,type:comment]
    HINDSIGHT_API_KEY: ENC[AES256_GCM,data:bA7S0ccmHSbok//eyBTIUKGlT6IGocu/NO8peHN4DD3StcWTeMx/Y46SQ51PBbMtYKyy,iv:Cf6gnOG9+AcaSmvHnP5CJMPpVqLrZGmwQyfEmOjz6eg=,tag:N9hk7Xp3bLY6FzBIsOOdFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Y05WMGtHbi9KYjBCbVRG
            N1AzSGRzVGNNRmhSSG5IM1ZpRkRvcUp1bVJJCk9wRTM2ekVtY05haXg0b0JlODBw
            VEdvNHFyekkwYU40UWRHcGFUM1FUNDAKLS0tIEFvQkV3cEx3MnVQZUVndzRoc2lx
            dHNxRWpqeFhqdW4zNlJpM0c5TXlETjAKqnMrGuIGHuAE6ZG+9mQ1nub75KNLJYyJ
            66hNKlhyg9Lm2DthwGcRoPVczZJYpBOUKk7i6NrJXitEqG7odgQaMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T06:25:55Z"
    mac: ENC[AES256_GCM,data:XxKXWzakpnJD5La2qmh6aR9WaZA2mhnE/1SMt8RaaRrA+Wi4tSaMtnTKXHOMNjMgBSMEW/C/LLdAnwCvALi/CnDVbTFUPcETwREpe4gF6AiV+71LvN3wAjVthe9Sa3BirrTEf22/RBQYQ67Eck7UEkhNmOYHWqB4QBhlOlNAuwA=,iv:6vwG8vSRsjoLoAtz2xELT+/1NtFzekwIgVZaL8Qup28=,tag:+c8H3DbE92ahtU9pBZQXuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
