apiVersion: v1
kind: Secret
metadata:
    name: hermes-credentials
    namespace: hermes-agent
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ""
    GEMINI_API_KEY: ENC[AES256_GCM,data:zIzpP9hzJioTLq8tvlrOc2sBG7+xwatZAdtBFrlgcrSNct7knPge,iv:15ZQHFvZ57UdnMQwKD6ON4IKnPYsHiC4zpZSfpKMtes=,tag:MEh0q9rYnYCLFKc/CuevQg==,type:str]
    HASS_TOKEN: ENC[AES256_GCM,data:tctRJU1rGqReurABk4zGejeNSb/2OcPz76AFQYq20CFcjvF8U5e4YrR0kIsRrMvJyJUgPd9knqZvz0psXMmmzo12XZmUBQXMnVHWoGWz8HCe10c7oL5TufKNC7W9LX2LBmnvz+FucIEkRm5lGr+IF0SPLWspix3YaPQ920tePPat4fB7nafIflLhPqDr9aoyqf/G7GUhXqqWqrNlzkf+DeMA1B5zw5M0cpq89/uaIt623Y4d60QM,iv:vGK16iK5dlHl8PTkpP4HcpJCDlhzmO/Jbl3nohvSJpE=,tag:NL8OGq9l2Xgw25BZgCTU2g==,type:str]
    PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:55PVRv4HMfyDRc3yVKLj0ycuKLle,iv:SPpU+Q1Z4oDjUJd22WkPkb6NAU9xUxaHN5AkQCLHBTk=,tag:feU7/fgepvb0yQewjSfX6A==,type:str]
    PROXMOX_TOKEN_VALUE: ENC[AES256_GCM,data:pcSDjlb2vv4slrPvRc2AIwCdzpGIvL2moid7OSkoJIh0Lrz0,iv:iRdXHMdgHLZem8Lv/ovB49zuU72d+ga17iXSkkx90AU=,tag:67EJbvEx3f9uiE02rlLpWw==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:51kfz3AD8PryNSOVHUeZZIq20i2ICLeOTwB+6c58gMiH3oMZowHasa4tLRJxTTWVxNrGrQyOBZs2Zci0PFQJfg==,iv:lb1VBXkqGKx30d1+q7zlLHtZ0hHMtXlM6sputemle0U=,tag:4Wd+1/OysIw1ztZJfE1NEA==,type:str]
    BESZEL_USER: ENC[AES256_GCM,data:SN/MOdLqEN/9q9lPqqyt9jalZ2LkFA==,iv:7C2/5Txr73oPpHJzdmlWY6r473ylvsu3HOpRj6L9TAw=,tag:b1c4+65Ui3Yqp/9pZWqK6Q==,type:str]
    BESZEL_PASSWORD: ENC[AES256_GCM,data:lsDUz8KnPBbPYC9AV3mZPuA=,iv:LxWotyVzSwdFWu/7M75SNRtAZ9wqTosPegg0WOwx4m0=,tag:QcagTKXw86W+MXFc9PMsWw==,type:str]
    GRAFANA_TOKEN: ENC[AES256_GCM,data:a8ig7Z+aYlmtW0IVx1ACx4+WMje0qU+tR4U3mbl+xWM6y+0XEGws5GoHMyjCig==,iv:7xxmWxIil7f+94iKVbaz51FiMREtYg1AAS/i45y8i4U=,tag:EPMg/Diu1+m/GJrfpeON3g==,type:str]
    PBS_TOKEN_ID: ENC[AES256_GCM,data:TG109EG9jWvqbcBpLWyG47IdroBIfD0Ng5jCc14=,iv:IouNVfzCyARr+QSCfP6WSLYmpmdANpa6CxXdakGrr7Q=,tag:xrG3IyZKDRDSSMgiRCufYg==,type:str]
    PBS_TOKEN_VALUE: ENC[AES256_GCM,data:Z4xbfEGRV2mBYBpVJvLSzfirTiISXDPxjK6ssvOxOPjYWcK5,iv:hwtFfOK1GiyhENG0WBM1n75TqSjFH1s3eqKQcPdhEuA=,tag:wjblByKzyfO7P7tnYwCifA==,type:str]
    SSH_PRIVATE_KEY: ENC[AES256_GCM,data:R75ZnP4ibaP0PgtqG6TavVGJfjIQexRvCcFYgXC1FeQjgkOgF7UgenPezuFP9hP3dYzj/UeEsEeZB9pHCjUWpFEyKVnrKmDXCyzc4ZcrV32e5sezc9EopfRymRtbNJcYyDlQqTU9w4E2GQZ6ATiNIdf4afkOsHuiDTZfxdAatFdORP3rz375PuAXBFcu6JBV0iMzhNXdrwxLQjPaGFoUi54Wa3lPk8XY5I8YpeO23iMuOZKa9IUKBlMw+uf2UDMpCNDylFbslVa3Q5wGb3804KKeO5u7HWu3sWSvtN07Myk70zttuVDUnnS6EbYkeYOlRAs685F77GTWX2/MbgZO9iEAtuXhNP25KDVJTad3omNFxnJHsUgQOodH5uO9XTYPHzTZOicUapbG1BQa7Vmh2cAoL6kxC8VqrDPxxSl53uVDPgmPCki8BcjxMBDpBkho6qZfjYJfgFxlpxvASpsk9kA7+mreYIBRp+hspIFZTC2DBYQwwT9P4k5e9LT6IycGtOWmfWSp1Uw8ORCcWoTry8JfUPnbYmtEp10rReongyDmex9nMVqafl853TwbNpoJ,iv:XBvaETvXb00iMXzBZ8rEiq9q37XuFA8ztAIoo6PE9VA=,tag:fL+njRTqQpNs6ZAZ3woM3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZWdxdkFFSVpCRllhVXFY
            R0l1RFpkak9FNmhzbDJSNGZvaTNsVzJOcm1NCjRwOWhERTMxYnlmZGE5LzFlRVIw
            dFV5N1N3blU2RDlBZStaMzFkWmordjQKLS0tIEVpWmpYSzhINjlxUHBZTXY1WEpx
            RTJQV3lwYVBOYmNoUVM4YW5mbHlvY0UKfX3pOjYEqzZohgsuH51wH/Ox+5l1N/HA
            CbKrWqvaqw+z+9+Ev4pRX+nsYU+1uKzhUN3BG90EcfhNlIdaCUcsFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T08:08:00Z"
    mac: ENC[AES256_GCM,data:i4bDq7H/tHP5X/LIiJZHSEAsWgPds3QwlJWicpvb43BHR5CZdUcqkS64HC5iVBO/8Bb8+ksWyHRDMnukmyhFGv6jw5VdvOnl/mZMgJu8V1o7jPG6GZPbrflbs0pUFg639yW9EvIczqDunzXq5BQuTEg7rjvjhEtwSL9P9lUbCxw=,iv:vOgjtzMUqgq4qG1F4NRDXGFaiHuvBNx1bcQPW2stkUg=,tag:4DTuCkzQsq98+LFOzIm6Jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
