apiVersion: v1
kind: Secret
metadata:
    name: hermes-credentials
    namespace: hermes-agent
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ""
    GEMINI_API_KEY: ENC[AES256_GCM,data:ja8GeirC6ZrYVSYoDGHIRc3l/e654RN5SZm67QdG+y8iQ0pVFjcE,iv:ufu+yNQdQ1tIpjA2gXF6AjDeeTZe48iK/zHWoGV8hLw=,tag:gldEhyqJihJjq2CHYvpKcw==,type:str]
    HASS_TOKEN: ENC[AES256_GCM,data:QJB1vTdFvb2oU+oLaL02mHRms1AfUCAflSl5B8A/SbOofbitle5N2dtbHB/Sah5lJECvA4B8E1+/Gh6fw+KQ3kJxNWhgRKXU8OBG+SOiRbZzXWt8bUoxM8O8rFDIv1d03Uy50jjzZPPGhQ+Gvic3Pvm+CMF4wqEAlxW0jZLAO9rS38uRZKtlri+dviKy8ndF6gt2BxYiE+FQq/7vFa5Jxul8F1fExWyowFu2xx/SLF+F6JSC+UcX,iv:f+RZ+3sodbBaHLHuGwz/cASGIRu4V+4jgH3VoXPJIfk=,tag:crWXMoFD3L3USKQ/S0iNJg==,type:str]
    PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:hGIfdRiozekbIL29oFMr6+INN8i5,iv:UxnEbWdF4GvuzVPuvk3SQywJp5z4jXPZOugg/adATFk=,tag:Jn3SYoMvwaaMtwdqowLgOQ==,type:str]
    PROXMOX_TOKEN_VALUE: ENC[AES256_GCM,data:PRVlzqZ5b56rcZzNcd2wFZRcKWNoEmbmoBLg9Hq/YU0j+E0I,iv:k+p76iM/raXQdj+RMazfZZrabXT35LMT5s92wI1LxWE=,tag:r2r2nrbLzJeR6m6mLO8JHQ==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:WXaGF30vnaFNs1MzHjlb2OPSeCEf77VKDXxkgfqMhmwNSFItpXW8Kcil2KIm3XY+TmAiaPhCTXIk34zC5MFbIw==,iv:zi9a6kHdp7nlXgBv7KUzXqo8xS/0+8mPe3vNXUg+cww=,tag:uZ4UWED1siOcjRUXKt+Idw==,type:str]
    BESZEL_USER: ENC[AES256_GCM,data:rwbFwceFLaTHs+SZhYGi8Jl3aEX/0g==,iv:D0QQ9+EOTPYMiESvn1/b0w43X+yfY3d5q0rKatEHkMM=,tag:jFYk0mT35rK+ky96Wu6BIA==,type:str]
    BESZEL_PASSWORD: ENC[AES256_GCM,data:kKIMlvTTKisSUZ/Em/fi1fc=,iv:xiqJFu18BSRtRHC/s44uoosskOCfpF6OEHofNpRqsQM=,tag:tjOC9y/PBOUavgQI+CmQtg==,type:str]
    GRAFANA_TOKEN: ENC[AES256_GCM,data:9R72EZOGm7/BaJk801pHi3Ilt24sQ5XN1ouuk14tWorpyaVGB2deXyv7sPIwWw==,iv:YW1XLQyeZcCWlEXNjN/KlrQphuxnaGg2HufXpYh1/JE=,tag:Ts24rWzOQ21yVs8wkjS8Cg==,type:str]
    PBS_TOKEN_ID: ENC[AES256_GCM,data:DcoXDROQ1BRyY9cCkHvfLL6HE/Nj07sa8fh8ZlU=,iv:b85IG6CrRyDkR09QnVeUupk5lhzQozKhUvmbidPQyf0=,tag:5S8sZHH8s68Q1yP1F75YeQ==,type:str]
    PBS_TOKEN_VALUE: ENC[AES256_GCM,data:RzF8CMCUBLrmSEV+j3cSwpQF8VJMXISzlaseBVgSAvtF38zX,iv:1543GuiZLF1blwo0xOoc5SxQ6zxBpP61Ih1fGLmcTJM=,tag:kNhyD6Ewo3RGhl9yj8/5OQ==,type:str]
    SSH_PRIVATE_KEY: ENC[AES256_GCM,data:TftrUfpY5PtT74ZXt08AVu8pVrFbb9AR+cKkjJxhQGX/7DtkibUuGM5Dc8pC21ceEbVMA71j5uiwtNnzPIvz9EyM3X5YpQmbDuluawZEUFoOnZbPzUi3BuLsBAnkbZSCGtJ5PcSbfyl6wYIhQSGqnYHURp0v/XbbdeGfPZMu30jvR1UErnXD0j6QfV94sHSr3dVIIq5Brei0/bE8slVxLEUvV83uMFXcxrUda7bhlk+amHZzdZt5ZczlP2F1zFJkbo/LSCNdXtzmj7egXSZ11WQ67X8VcHvyuqMdrQHdjR9sReXRtSe/JAvq71ux4KIOlqboLd6hTDJhUKqV/eNYOw7+IEKaIx87EKDHQ+ZRBAbegU5cvpdbO585hlHlX3ZPDGThwDyH96HC1KOzxWcCE9kmI9cMZqHc1Ay6xOGI9omCXifjV7lWTI9p6RieW+EuJ9OfCoJtVFsyCb0in3rJJQgkpnFfp7HJ51iMTP2tM3BZbv63khH3hVBw5zjhyhl7rewHAUcbYGxZ6ppEWL5GwWI12BTqH9wU/yZbnHdiFvOhTRCQoij9GIavrYbpZPo=,iv:SAbuaW7jLnlXGEjGWo0vgA/DCWPBl+cmFr0QoNoeEG8=,tag:61Hdyo/3X7hLO9fK/VJPLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOTd1V1l6UzhMMlk5MDEy
            WGhyRHA0R0xDOUxmY1hDTXhZSHUyRUZoTURzCnNBQ1RXWWtNWXFwa0E3ZXlxVWlw
            UTRyZTdCZ3B5Y045UStvWlZPL20vYlEKLS0tIEdRalJkenl0QXpPa3NwNHdPeFhw
            RG9laXIybFlqczdIYmgwVURxZzhuQ28K5PuhKbx5TzhpqwpyEwQsjTXqRPzJmvGc
            SdjgZugemJxXL00AR9nDgu/3jzYEi4JpJiFBfmi95QeFI2r6nLHK6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T07:15:48Z"
    mac: ENC[AES256_GCM,data:q8MPDlwMaFjZzwEjtRs/hYFo30iwVRZF6t2wtbN6mAlcDt2RShuJwz3LxGfXmcjcPVIIOmdvDOT7kH/3+dVVKMggQxP2nQlHhWvRtaYet3M4/UWlHtq2JnIvE6HZP8VzIa7A4YOPvHefQ01+Ah218b0EezZBbwK+oy+rAJFnMMA=,iv:TtjzXH8QWDXsH0ko1i/o52f+w93sBoywV0NfD34DHPE=,tag:B6eNIUhiVc3dNVeQQH40UA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
