apiVersion: v1
kind: Secret
metadata:
    name: hermes-credentials
    namespace: hermes-agent
type: Opaque
stringData:
    ANTHROPIC_API_KEY: ""
    GEMINI_API_KEY: ENC[AES256_GCM,data:D5sn/GNkNLUfptAWb64/B9I8fLr+p3eZXjmVQ1zOpaPBXGbV+kUF,iv:5WFUSssIzQQXEsf8wvdiApK7Lnp1w9CYLs26WemJxlg=,tag:2w5A7CfdG1q0Wdpc5tZyWw==,type:str]
    HASS_TOKEN: ENC[AES256_GCM,data:e0kTJmgjgFd9PAUYPmJX/EN+ynzgTPa+DT3UHH5MtHI9UjVEBgCGLUg4CGtwy8mzJj/Y+Mt5JEGWREOMofXVWywJPC+RSX7LwGSqdMCxSW+Fdu7eqXj1E6NlUNvAH458tBENceJlqMV1iEbUq4wv0X8lEkcvjBRfGbkX5SZnOBVvu3fGA588Gn3HQBRn5qrhTbb4vQh1zYFDhbOX9eGiRR+6LeIlcXQwPSrmAYF7RtLgjqTnxoZp,iv:68m+5vTRFUJrYJ1ilUwsPBF6XpWqZ3kJIhNoQrbk54Y=,tag:25/6mAHuL0ZaDz8tVXh9DQ==,type:str]
    PROXMOX_TOKEN_ID: ENC[AES256_GCM,data:WQBq6VoZM2Aj9cJfYY07RQI0l9dA,iv:6EEalObXK8o+4ujuWWDEk9UQ/A0Pu/TCLe03zL84lg8=,tag:QF4kBQs/XNjF/HLW8E8nkQ==,type:str]
    PROXMOX_TOKEN_VALUE: ENC[AES256_GCM,data:LO67jXinl3NY68KOd3ae8ACIgK1L2bgopWUF1hlwincYcGvG,iv:L+4snSAJh+p6W5oopYdotuhXO6QmL4RBok4Dit9T1Sc=,tag:qOCBr25gwQcE0aPtuvKu/A==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:Zpxp88o5VmEMJEfHVG1wUhVABzefUEX9O/5ugg06iZ846fI0gKn7OpJ+s4pmlm8rtSJYp7i6AbbgGE/cAgQS8A==,iv:AyOg3Ncjgv/Muw8hlYl9Uzaa1p6nclBAp9ItZlVD+hM=,tag:wFKmjQMP803UHjHzBV5JmQ==,type:str]
    BESZEL_USER: ENC[AES256_GCM,data:lwZ4/5EJXlzv5sP7ZNrnhKOjGfi2qw==,iv:jVf+oLORfNgDhGpMUV0qC/IXb2u0C8DxkVnyk32G36E=,tag:I/ivSb8ff/set+Uek0Xd1Q==,type:str]
    BESZEL_PASSWORD: ENC[AES256_GCM,data:cOeXMa6Q7Y+AQZJ2TksC4+o=,iv:8Wl7RIQvZfRfHjJZdEZvMJOm3Xkdd3EFZ1V2ogPfXlY=,tag:nNzwd0165R72qeqYDUoIFw==,type:str]
    GRAFANA_TOKEN: ENC[AES256_GCM,data:80r0t5Reh+vFlYQQYE0tavgszNsT6H8K6DV4RKSYeJu+sguXE9/bgWADFyTuhA==,iv:wlb2ZfyqufbqHLJxn0Kny8Eoxd9LQfh4kcMjWvDW5II=,tag:hbK+ILguUZEWZnwWJiWZ/Q==,type:str]
    PBS_TOKEN_ID: ENC[AES256_GCM,data:j1z1mxm3aJF0sxKd8vipQbR18U6i8NfbOld/IDI=,iv:cxxoQSrgSYSPT7zAQARTNv1ZVqTZgz/ExPb1lm4sh4A=,tag:VbtjFIDbrtfCwGauKwzi5A==,type:str]
    PBS_TOKEN_VALUE: ENC[AES256_GCM,data:eZUdgwVpcLD5Iy2g/Vnz7Anw6A2fgpEHhWBzTZEFhut7UGJW,iv:GWWHMrOHY/wEV6vUReVYM6ID0Pavg1bf/5Mo99XjHfc=,tag:Ll49CaEDJWtuqgqTXNu4Nw==,type:str]
    GOTIFY_TOKEN: ENC[AES256_GCM,data:9j9T6BKOrdwHAn96oHHR,iv:c+9/skVyXU6xb39MMQjPm4rOwdrkr5H2vikTooUnMtY=,tag:z1Km6Wn6OqafYgUu0e9B9A==,type:str]
    SSH_PRIVATE_KEY: ENC[AES256_GCM,data:9PjVQXOTgmPqgOUSB1IgX8AyoJWN0+y6G2cSwo6gelGeD0EKO88kZrYg6kjYC5TEoN0YkGRYsGjA5P5aFUGY47AqoI4Wgj6yhFKAnnisynHMzZC+ZNUGl+0J3iaJxCCp66IcLaKloz9yh4le2QAZ9eC+iSozPq5acWG7gAs21/+PcbJD1wz860q0AeavQ9v1xCaHhl4whDVnCJhOHMsqgmM2AOVR2QZFDhV/4ZkWGQDVD3a33YWILNq5L+LWjsVziZ4B4FFM8K7u/ObYbCcNJiQD3eBNhqmm46zoTD8Bc2lVenZYpaShOxUhalNozafV5d5ucEbD626pJoVHpW64nNUfWhNtSOL6zYRMpCiCuwxOZULWUJ2U3p7IuP4mFsPtQB4aScKCebxUipUVKcstg2w8aPZzrHlm5F1m9lpAAKJOYEzUsiXErTXsU86kGYQze1IMgnJ1Cm3b6wy0u7LrytH3Up7ZFlyYJrLre0AbwrpKwMvVupNy5pue9HTmry8vdQcLjlXCM6Lhf7FRe//QSYyk4zA4kRWJMdb1wMKu3Etv3OtfXmKnncrlSBPoxQ6s,iv:w+BWTzEOas1OPrC0PxrousGOzVhmUuZJCWw09L2tAhQ=,tag:Vet/PvcarzFB9Zh50YEw7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQWl4Q2E0SlRDM3U4NTVF
            KzNwRHAvekxlbXdkbjd5MXNWUFY2RlM3bkF3Cm92NlhUU3J2OURUR2RqTXRqZGh5
            bXl3NUlQNHQxaEhnV3NsYjZISGVLVE0KLS0tIE1yMlF4dTFEUFRJWGVRSHA1UjFh
            d210L21KYlUwQmpLcHVEV21nbkszSU0KnRUGNmZHDns8Xq8PAQupp5kAhUo+m68c
            2OBKWW2J7nlaDGzs5gTaYnAW0RacMGAyAADpsqsuR2WiyuWVh5uCTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T08:47:20Z"
    mac: ENC[AES256_GCM,data:kgUHMbwD3d9hSCAEXZZOk+KMCD+1QXMxh1v9Khn7iI2mupcmEEA0DJLjWuhilQQg2F/HWersl920Lpo+GLNg7xQtzYJUe44l3shX94sE6TR1u+0s4p4+Qomvc8Q55i1ULLZ6GQ16gBo6pjPlm1K5EJ06P7pN/K4sMohHuse2SVw=,iv:HNEodp/OyR2qgjV1xxxSoXFIJLsxkfHRcvwhl5bbRJw=,tag:KzG4JXRNwf6704HCis5E2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
