# Encrypt with SOPS before committing:
#   sops --encrypt --in-place secret.yaml
#
# Generate encryption key:
#   openssl rand -hex 32
apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    #ENC[AES256_GCM,data:WZPirqGBP2XoVZbvmnGxDA2xbOo+GB5HaZBQb+gwbNiPhK+qE+sRBybHV1pxrIp3A2QPH0VQyA+Yr823cSTOyPgsnJNbl+kSMSEqiidT/UN9CA==,iv:J9OpkhK00P5K3DxH7RLNmRwkUEIq3OYJqCU+RS9uYT8=,tag:GRcGjK2GVjn3Zi/7AVKKLw==,type:comment]
    #ENC[AES256_GCM,data:Pj7Vl7+81aRgfaUt4OYiXF6TNvpCKoV9rJNQQ9Hc1oojV21F1rqY7+8t+I3Uf9St4iCMNdckvkcQUY6mKXxr1kKljDqkQlrCfgXHIzEab3en,iv:XIi/stMu20Z1mIIvFR3NXaztAih73qXd0m3lYtTTrfE=,tag:w+rXHCvg2h1m7sJy+Z9KWg==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:r+OeNRf9yUbyVqlrhYKEN3+xazBzX+PcyXkykwb+O2k=,iv:vessZYYmMESzHAYmJAR07GPBzvq1GkcWP7giRO07O+k=,tag:Zr7XDGP2suoN5GpUxCYQIg==,type:str]
    #ENC[AES256_GCM,data:btE9QT2nJRDqBf31cmWPOSSDbzFSsZvx+O1Z39y+uLLOxJsYTLil1Kk6oLrNy+AO8FFwBZKtKa+F2thZt2NPiQ==,iv:Ag+53KbemOUPedbfQj159E8/pUAvA7o5WqEDRBjusFo=,tag:gElXtYhIZVzv8OhnD+mPmw==,type:comment]
    N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:X4RUiaGb7PDF6CGdLxAkDjGxTnLFNbSY/WohjFADvzE=,iv:LyDbttVji1+Q/dv67qVqOA4+iEQ4RYUX5q1IPsXcgiY=,tag:uI7zTdSRNPeM7gq7Bock2Q==,type:str]
    #ENC[AES256_GCM,data:8K4FjygC2M05CdAC0sacQiHR273XLh0Ufw4cFHsFEPioI2UFPcookh9ljQM6rej6QNbNZA==,iv:UW9HVmDbNHGk7iG+26p4J9vULEVdkEQFpEgwZ7drkG0=,tag:ViOaEzrUCEOvWouP7Rudzw==,type:comment]
    UPSNAP_USERNAME: ENC[AES256_GCM,data:uncjL4oZ8g==,iv:7ijIwGCTRnX6PQmMJkfCGFKZq0PLu6f+2Voj+LhAiR4=,tag:qRUsZy5LW9F5NDpNxPOneA==,type:str]
    UPSNAP_PASSWORD: ENC[AES256_GCM,data:B+wAjFS7BJj0SFWUo3HT5A==,iv:k4tp4HFXOhfQ41jFNYwNUrcp3Z1rDsN5wce2O2AxjYY=,tag:8eILW8qKjn1XcEagaZoviQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K3ZyL1RydDBTNDVheXZh
            eUorSDlNTUZSUVdFV3FzYk0rS1N3R0pwVUc0CnBYUDdtRXJTVmhKVkFROUx3N0FI
            UHN1OFFBT01rTGptdkdXY2grcHhPSVUKLS0tIHpuWTRHRVFVblptVkNvaG80d3oy
            L0U3bGc5dEZ0ZXJuMVJpcjBHVEVhNkkKMgaCtkmnjoGlKxD50emxH2Vn9mFlpik3
            VTCYZjT5FRRN84p0wxNqhNETpDePK13a6d+nAkXiLuceNmjLPlFgJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T05:48:41Z"
    mac: ENC[AES256_GCM,data:4TpgOaou10l4sL8FCIQc5/SoXRy10rZhbEAiBXBZSd8pG846FXmnUzA+1ZoZj/2PHk3a0Ntjl7gKoBRznJ88VVmNWI3olDZF6GCxM2emXhHJEYwdK2+GD/trYwwHS4IQUuSh0xv7vR4R3eZBLBoK9BNHZmLcIZc61c7s9MVWbuk=,iv:XmsRbFSleoWyk+GeefMttSxzszkd8RcoMipq7fyQpUs=,tag:nb9IxzO2zk3FnH4h1Q/qFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
