#ENC[AES256_GCM,data:uLOIhE1APNnzd7socH9OxHz7VAtywnMMFfX6shok1SpQS5itQg==,iv:VVtPPXs0P6xcGADo9zjWAde2e3qJ2LFRMfJHJNzbWlE=,tag:HbWETd6abCcmiMDWiL/6gw==,type:comment]
#ENC[AES256_GCM,data:p/D80G8aMYg3TJH5iffagXx/NMPkFKVmEzG6pUWbBp96ZQmHMZ9QRQ==,iv:ef6YLtF3WVoJG8AwaKnxgj2Ck6+vB7od7FYSltD7Anw=,tag:j3AJlP+UccRMoCbTnbgX0g==,type:comment]
#
#ENC[AES256_GCM,data:kWky4U7OQxIJnbfMBPri0oCMOXIa2XuzqQ==,iv:jVwHZHNFQQnA70LepnX0XhXvn5m7stotFVmnfUWrEOI=,tag:8qpfBfQM8gXXqXCDPUZhXQ==,type:comment]
#ENC[AES256_GCM,data:IRQRuWnjt5hkRUWX2iCKwD6eWRZDjb0=,iv:hSKBHFQhm/ZAClZ8dvgDObk8b/oUrYw9g17gKhDBEC0=,tag:vr5mW/jXFfBLbXzUu27Mug==,type:comment]
apiVersion: ENC[AES256_GCM,data:Yoc=,iv:LHQypvVXglAVoIxSmLn5WI/976Ra0KoYAjT0+R5TwbE=,tag:SuZXDacqzwyySLsQzbBtIQ==,type:str]
kind: ENC[AES256_GCM,data:/LvgSKIh,iv:G+wzgtCY91vMW8w4ZrTxjHTBKYC7Kwa0UE6qIj08LIY=,tag:Znb/hWz7gZBqAO07/pwh2w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZPb69b/R/aSV1Qo=,iv:83IK8kpN4ekr/rem8YWEgsUdvw0ZqSOZi0xIUMgJ5y0=,tag:lNvQGYSmG+VXLfx4fFCwZA==,type:str]
    namespace: ENC[AES256_GCM,data:IA/6,iv:deZmqR84DGeHhLlKmOu4zlaWzY74CPTlvfdeLNJJiE4=,tag:5u0DB0QzpYaLxiLt0+cyAw==,type:str]
type: ENC[AES256_GCM,data:sNvOEb8t,iv:SsfpUvXKGZVX+VPpdoRVrspiC+QymhFf/QrsBc9uRSc=,tag:PAROp6dLs0U/hJL6V0yA1Q==,type:str]
stringData:
    #ENC[AES256_GCM,data:fxbBL+TgumbMOrwAqeNMZPJRMTy2N3Uo8WPOVeeLADtXtj4dYDtMiBOhB/aYI4WCEy+O3PNSEEjwW0t+CXiEamJbf/G9RH+NMB4qyJj21s47qw==,iv:0P31IcC7P35DlB8OnWD+yzTy73sZ2x6LKuo9qpNnGwg=,tag:e2Bu9RqQz5zayq+9OLJZNw==,type:comment]
    #ENC[AES256_GCM,data:AAfk4PJLEs4xc/Fdbf0yiQUR4U52htyZA57PxIUfck0aV0VcTzqvOTXLRmkLRGh686jkIboZOrGOQ2avmTBPZ++ycAzaPvsbVtpi/pOMh066,iv:BoaBUrg3vBPwhzXW+x/OeioBoQWg9lup6RaG80K+XiM=,tag:LQkKCHh/dP1oEEZQKj9Uag==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:ycGNiHT4OoxPllhhPy0MW6LNyTuXTt9piI3N2f/Hp4M=,iv:mTLm9rMw2QUBOrVbrU3MtUKnW3cGYbclNcjbcvdnRjc=,tag:6mY+KBpJaclV9paSU/FzLA==,type:str]
    #ENC[AES256_GCM,data:1eTXbKPiI/TcL0SjrPvE9yW+++FrxZ0ZMex2ebtm/eKhhzgWrMKdEjLlnu/SAnYOqjYmCNNbAtqkpO5r9vNOmw==,iv:OUhZ/s7DxHewq88NDKWiOobD3yVgRadHwGiAJj00P5I=,tag:FuhnwlMVLJ1XP5GZKBj9rA==,type:comment]
    N8N_RUNNERS_AUTH_TOKEN: ENC[AES256_GCM,data:VPFutA7bgJJHx8BB5TgIGr29nCHIbU+byuVg8mmUXdg=,iv:3KPDmNUe8mgO+ayAEGCaHfhl59xcdzQoo1I5Fa8PVKI=,tag:cJwIW517ZY0nbhilJe5KXA==,type:str]
    #ENC[AES256_GCM,data:cF8aeZif7xczWK5OvPmzfVdUtFZgbobithSY9+HBWu5C+HGfYN3sjhWxGI6KbUiNYrZv9Q==,iv:qwJWr4TX0d96nqm6etYH3e7H5grqX7cHH9iZRZCaWYQ=,tag:ykQDB2LRLoyY2LBpEN19yg==,type:comment]
    UPSNAP_USERNAME: ENC[AES256_GCM,data:SbjfMy8Msg==,iv:hoWniRQCTwoNOy3XfKX9CAJB2mgHEnAZRIQljlvqb44=,tag:eXUvl7PC5n1VLFcBL69jzg==,type:str]
    UPSNAP_PASSWORD: ENC[AES256_GCM,data:8JDqLQ8ka2ew53aQ2EFq2g==,iv:XfVfH9emBNHQc3qvRfgh/zE3Om36Y+AaacoF9xVFPjA=,tag:R+2EOO+0THXyJbRi4NkZLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gqzu544u299sfdfnsrxxgz6dw7vl7rk8p50mazkhvdwffwlf3msdr4q0t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdWIvWFlJNFFaZDl6Snpn
            MVhIenVtZmtmcW9QR1ppMkpnVnpXV3FCdmtJCnVlV1BDZEJLRlptS1hmbG1xMjkr
            L3QzbEh3M0gxTjBvM29zS2NMUGQzdWMKLS0tIDFXVWx1VEM1SU1FRHdJYXo1ait2
            RVBuRldqS0VsSXBIN3UwRHFaQ0tva0EKCHxKdRVNx560U3NoJtsN6/+3Xqe/LAPO
            Qx9Dm8ls/EbH3yEbql7BcpADH2VKVsB1AgcqquPuXgGHjzFBR4luCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T04:41:34Z"
    mac: ENC[AES256_GCM,data:WXX7pZ2KH910SoSTL1lOv+PTE2lUVjWPWxsUrgzJEaTEHlb6MRnctDCy9hoErUmWR2y+L9iL1xI7HuKa86TOwz12y2sBdH60SFedYD9B8K/0NY5jkGACnduafjOGRzlkWIeB/I0AnrP/o2IyHkHlYBzzbpOq6LybcdMBWmOEt4I=,iv:ev1H+LBbP6xn4GWE+ZAtGvwF3DLEt51LsdA6UEsCqrY=,tag:Zr39gHd8KDuhnWN+fTtUQA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
